// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/payment.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PaymentMethod representa os métodos de pagamento disponíveis
type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED PaymentMethod = 0
	PaymentMethod_PAYMENT_METHOD_CREDIT_CARD PaymentMethod = 1
	PaymentMethod_PAYMENT_METHOD_DEBIT_CARD  PaymentMethod = 2
	PaymentMethod_PAYMENT_METHOD_PIX         PaymentMethod = 3
	PaymentMethod_PAYMENT_METHOD_BOLETO      PaymentMethod = 4
	PaymentMethod_PAYMENT_METHOD_PAYPAL      PaymentMethod = 5
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "PAYMENT_METHOD_CREDIT_CARD",
		2: "PAYMENT_METHOD_DEBIT_CARD",
		3: "PAYMENT_METHOD_PIX",
		4: "PAYMENT_METHOD_BOLETO",
		5: "PAYMENT_METHOD_PAYPAL",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED": 0,
		"PAYMENT_METHOD_CREDIT_CARD": 1,
		"PAYMENT_METHOD_DEBIT_CARD":  2,
		"PAYMENT_METHOD_PIX":         3,
		"PAYMENT_METHOD_BOLETO":      4,
		"PAYMENT_METHOD_PAYPAL":      5,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_proto_payment_proto_enumTypes[0]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{0}
}

// PaymentStatus representa os status de um pagamento
type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_PROCESSING  PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_APPROVED    PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_DECLINED    PaymentStatus = 4
	PaymentStatus_PAYMENT_STATUS_CANCELED    PaymentStatus = 5
	PaymentStatus_PAYMENT_STATUS_REFUNDED    PaymentStatus = 6
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_PROCESSING",
		3: "PAYMENT_STATUS_APPROVED",
		4: "PAYMENT_STATUS_DECLINED",
		5: "PAYMENT_STATUS_CANCELED",
		6: "PAYMENT_STATUS_REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_PROCESSING":  2,
		"PAYMENT_STATUS_APPROVED":    3,
		"PAYMENT_STATUS_DECLINED":    4,
		"PAYMENT_STATUS_CANCELED":    5,
		"PAYMENT_STATUS_REFUNDED":    6,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_payment_proto_enumTypes[1].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_proto_payment_proto_enumTypes[1]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{1}
}

// ProcessPaymentRequest é a requisição para processar um pagamento
type ProcessPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod PaymentMethod          `protobuf:"varint,3,opt,name=payment_method,json=paymentMethod,proto3,enum=payment.PaymentMethod" json:"payment_method,omitempty"`
	CustomerEmail string                 `protobuf:"bytes,4,opt,name=customer_email,json=customerEmail,proto3" json:"customer_email,omitempty"`
	CustomerName  string                 `protobuf:"bytes,5,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	// Informações específicas do método de pagamento
	//
	// Types that are valid to be assigned to PaymentDetails:
	//
	//	*ProcessPaymentRequest_CardDetails
	//	*ProcessPaymentRequest_PixDetails
	//	*ProcessPaymentRequest_BoletoDetails
	PaymentDetails isProcessPaymentRequest_PaymentDetails `protobuf_oneof:"payment_details"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessPaymentRequest) Reset() {
	*x = ProcessPaymentRequest{}
	mi := &file_proto_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentRequest) ProtoMessage() {}

func (x *ProcessPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessPaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ProcessPaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ProcessPaymentRequest) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *ProcessPaymentRequest) GetCustomerEmail() string {
	if x != nil {
		return x.CustomerEmail
	}
	return ""
}

func (x *ProcessPaymentRequest) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *ProcessPaymentRequest) GetPaymentDetails() isProcessPaymentRequest_PaymentDetails {
	if x != nil {
		return x.PaymentDetails
	}
	return nil
}

func (x *ProcessPaymentRequest) GetCardDetails() *CardDetails {
	if x != nil {
		if x, ok := x.PaymentDetails.(*ProcessPaymentRequest_CardDetails); ok {
			return x.CardDetails
		}
	}
	return nil
}

func (x *ProcessPaymentRequest) GetPixDetails() *PixDetails {
	if x != nil {
		if x, ok := x.PaymentDetails.(*ProcessPaymentRequest_PixDetails); ok {
			return x.PixDetails
		}
	}
	return nil
}

func (x *ProcessPaymentRequest) GetBoletoDetails() *BoletoDetails {
	if x != nil {
		if x, ok := x.PaymentDetails.(*ProcessPaymentRequest_BoletoDetails); ok {
			return x.BoletoDetails
		}
	}
	return nil
}

type isProcessPaymentRequest_PaymentDetails interface {
	isProcessPaymentRequest_PaymentDetails()
}

type ProcessPaymentRequest_CardDetails struct {
	CardDetails *CardDetails `protobuf:"bytes,6,opt,name=card_details,json=cardDetails,proto3,oneof"`
}

type ProcessPaymentRequest_PixDetails struct {
	PixDetails *PixDetails `protobuf:"bytes,7,opt,name=pix_details,json=pixDetails,proto3,oneof"`
}

type ProcessPaymentRequest_BoletoDetails struct {
	BoletoDetails *BoletoDetails `protobuf:"bytes,8,opt,name=boleto_details,json=boletoDetails,proto3,oneof"`
}

func (*ProcessPaymentRequest_CardDetails) isProcessPaymentRequest_PaymentDetails() {}

func (*ProcessPaymentRequest_PixDetails) isProcessPaymentRequest_PaymentDetails() {}

func (*ProcessPaymentRequest_BoletoDetails) isProcessPaymentRequest_PaymentDetails() {}

// CardDetails contém informações do cartão
type CardDetails struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CardNumber     string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardHolderName string                 `protobuf:"bytes,2,opt,name=card_holder_name,json=cardHolderName,proto3" json:"card_holder_name,omitempty"`
	ExpiryDate     string                 `protobuf:"bytes,3,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"` // formato: MM/YY
	Cvv            string                 `protobuf:"bytes,4,opt,name=cvv,proto3" json:"cvv,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CardDetails) Reset() {
	*x = CardDetails{}
	mi := &file_proto_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardDetails) ProtoMessage() {}

func (x *CardDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardDetails.ProtoReflect.Descriptor instead.
func (*CardDetails) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CardDetails) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *CardDetails) GetCardHolderName() string {
	if x != nil {
		return x.CardHolderName
	}
	return ""
}

func (x *CardDetails) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *CardDetails) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

// PixDetails contém informações do PIX
type PixDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PixKey        string                 `protobuf:"bytes,1,opt,name=pix_key,json=pixKey,proto3" json:"pix_key,omitempty"` // CPF, CNPJ, email, telefone ou chave aleatória
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PixDetails) Reset() {
	*x = PixDetails{}
	mi := &file_proto_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PixDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PixDetails) ProtoMessage() {}

func (x *PixDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PixDetails.ProtoReflect.Descriptor instead.
func (*PixDetails) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{2}
}

func (x *PixDetails) GetPixKey() string {
	if x != nil {
		return x.PixKey
	}
	return ""
}

// BoletoDetails contém informações do boleto
type BoletoDetails struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CustomerDocument string                 `protobuf:"bytes,1,opt,name=customer_document,json=customerDocument,proto3" json:"customer_document,omitempty"` // CPF ou CNPJ
	DueDate          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BoletoDetails) Reset() {
	*x = BoletoDetails{}
	mi := &file_proto_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoletoDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoletoDetails) ProtoMessage() {}

func (x *BoletoDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoletoDetails.ProtoReflect.Descriptor instead.
func (*BoletoDetails) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{3}
}

func (x *BoletoDetails) GetCustomerDocument() string {
	if x != nil {
		return x.CustomerDocument
	}
	return ""
}

func (x *BoletoDetails) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

// ProcessPaymentResponse é a resposta do processamento de pagamento
type ProcessPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=payment.PaymentStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	TransactionId string                 `protobuf:"bytes,5,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // ID da transação no gateway de pagamento
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentResponse) Reset() {
	*x = ProcessPaymentResponse{}
	mi := &file_proto_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentResponse) ProtoMessage() {}

func (x *ProcessPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentResponse.ProtoReflect.Descriptor instead.
func (*ProcessPaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessPaymentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *ProcessPaymentResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ProcessPaymentResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *ProcessPaymentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProcessPaymentResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ProcessPaymentResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// GetPaymentRequest é a requisição para buscar um pagamento
type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_proto_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{5}
}

func (x *GetPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

// GetPaymentResponse é a resposta com detalhes do pagamento
type GetPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod PaymentMethod          `protobuf:"varint,4,opt,name=payment_method,json=paymentMethod,proto3,enum=payment.PaymentMethod" json:"payment_method,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=payment.PaymentStatus" json:"status,omitempty"`
	TransactionId string                 `protobuf:"bytes,6,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentResponse) Reset() {
	*x = GetPaymentResponse{}
	mi := &file_proto_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentResponse) ProtoMessage() {}

func (x *GetPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{6}
}

func (x *GetPaymentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *GetPaymentResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetPaymentResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetPaymentResponse) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *GetPaymentResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *GetPaymentResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *GetPaymentResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetPaymentResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CancelPaymentRequest é a requisição para cancelar um pagamento
type CancelPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPaymentRequest) Reset() {
	*x = CancelPaymentRequest{}
	mi := &file_proto_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPaymentRequest) ProtoMessage() {}

func (x *CancelPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPaymentRequest.ProtoReflect.Descriptor instead.
func (*CancelPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{7}
}

func (x *CancelPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CancelPaymentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// CancelPaymentResponse é a resposta do cancelamento
type CancelPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CanceledAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=canceled_at,json=canceledAt,proto3" json:"canceled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPaymentResponse) Reset() {
	*x = CancelPaymentResponse{}
	mi := &file_proto_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPaymentResponse) ProtoMessage() {}

func (x *CancelPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPaymentResponse.ProtoReflect.Descriptor instead.
func (*CancelPaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{8}
}

func (x *CancelPaymentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelPaymentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CancelPaymentResponse) GetCanceledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CanceledAt
	}
	return nil
}

// ListPaymentsRequest é a requisição para listar pagamentos
type ListPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsRequest) Reset() {
	*x = ListPaymentsRequest{}
	mi := &file_proto_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsRequest) ProtoMessage() {}

func (x *ListPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{9}
}

func (x *ListPaymentsRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// ListPaymentsResponse é a resposta com lista de pagamentos
type ListPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*GetPaymentResponse  `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsResponse) Reset() {
	*x = ListPaymentsResponse{}
	mi := &file_proto_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsResponse) ProtoMessage() {}

func (x *ListPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{10}
}

func (x *ListPaymentsResponse) GetPayments() []*GetPaymentResponse {
	if x != nil {
		return x.Payments
	}
	return nil
}

var File_proto_payment_proto protoreflect.FileDescriptor

const file_proto_payment_proto_rawDesc = "" +
	"\n" +
	"\x13proto/payment.proto\x12\apayment\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x03\n" +
	"\x15ProcessPaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12=\n" +
	"\x0epayment_method\x18\x03 \x01(\x0e2\x16.payment.PaymentMethodR\rpaymentMethod\x12%\n" +
	"\x0ecustomer_email\x18\x04 \x01(\tR\rcustomerEmail\x12#\n" +
	"\rcustomer_name\x18\x05 \x01(\tR\fcustomerName\x129\n" +
	"\fcard_details\x18\x06 \x01(\v2\x14.payment.CardDetailsH\x00R\vcardDetails\x126\n" +
	"\vpix_details\x18\a \x01(\v2\x13.payment.PixDetailsH\x00R\n" +
	"pixDetails\x12?\n" +
	"\x0eboleto_details\x18\b \x01(\v2\x16.payment.BoletoDetailsH\x00R\rboletoDetailsB\x11\n" +
	"\x0fpayment_details\"\x8b\x01\n" +
	"\vCardDetails\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12(\n" +
	"\x10card_holder_name\x18\x02 \x01(\tR\x0ecardHolderName\x12\x1f\n" +
	"\vexpiry_date\x18\x03 \x01(\tR\n" +
	"expiryDate\x12\x10\n" +
	"\x03cvv\x18\x04 \x01(\tR\x03cvv\"%\n" +
	"\n" +
	"PixDetails\x12\x17\n" +
	"\apix_key\x18\x01 \x01(\tR\x06pixKey\"s\n" +
	"\rBoletoDetails\x12+\n" +
	"\x11customer_document\x18\x01 \x01(\tR\x10customerDocument\x125\n" +
	"\bdue_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\"\xfe\x01\n" +
	"\x16ProcessPaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.payment.PaymentStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12%\n" +
	"\x0etransaction_id\x18\x05 \x01(\tR\rtransactionId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"2\n" +
	"\x11GetPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\"\xf2\x02\n" +
	"\x12GetPaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12=\n" +
	"\x0epayment_method\x18\x04 \x01(\x0e2\x16.payment.PaymentMethodR\rpaymentMethod\x12.\n" +
	"\x06status\x18\x05 \x01(\x0e2\x16.payment.PaymentStatusR\x06status\x12%\n" +
	"\x0etransaction_id\x18\x06 \x01(\tR\rtransactionId\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"M\n" +
	"\x14CancelPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x88\x01\n" +
	"\x15CancelPaymentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12;\n" +
	"\vcanceled_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"canceledAt\"0\n" +
	"\x13ListPaymentsRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"O\n" +
	"\x14ListPaymentsResponse\x127\n" +
	"\bpayments\x18\x01 \x03(\v2\x1b.payment.GetPaymentResponseR\bpayments*\xbc\x01\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_CREDIT_CARD\x10\x01\x12\x1d\n" +
	"\x19PAYMENT_METHOD_DEBIT_CARD\x10\x02\x12\x16\n" +
	"\x12PAYMENT_METHOD_PIX\x10\x03\x12\x19\n" +
	"\x15PAYMENT_METHOD_BOLETO\x10\x04\x12\x19\n" +
	"\x15PAYMENT_METHOD_PAYPAL\x10\x05*\xde\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19PAYMENT_STATUS_PROCESSING\x10\x02\x12\x1b\n" +
	"\x17PAYMENT_STATUS_APPROVED\x10\x03\x12\x1b\n" +
	"\x17PAYMENT_STATUS_DECLINED\x10\x04\x12\x1b\n" +
	"\x17PAYMENT_STATUS_CANCELED\x10\x05\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REFUNDED\x10\x062\xc7\x02\n" +
	"\x0ePaymentService\x12Q\n" +
	"\x0eProcessPayment\x12\x1e.payment.ProcessPaymentRequest\x1a\x1f.payment.ProcessPaymentResponse\x12E\n" +
	"\n" +
	"GetPayment\x12\x1a.payment.GetPaymentRequest\x1a\x1b.payment.GetPaymentResponse\x12N\n" +
	"\rCancelPayment\x12\x1d.payment.CancelPaymentRequest\x1a\x1e.payment.CancelPaymentResponse\x12K\n" +
	"\fListPayments\x12\x1c.payment.ListPaymentsRequest\x1a\x1d.payment.ListPaymentsResponseB\x10Z\x0epayments/protob\x06proto3"

var (
	file_proto_payment_proto_rawDescOnce sync.Once
	file_proto_payment_proto_rawDescData []byte
)

func file_proto_payment_proto_rawDescGZIP() []byte {
	file_proto_payment_proto_rawDescOnce.Do(func() {
		file_proto_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payment_proto_rawDesc), len(file_proto_payment_proto_rawDesc)))
	})
	return file_proto_payment_proto_rawDescData
}

var file_proto_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_payment_proto_goTypes = []any{
	(PaymentMethod)(0),             // 0: payment.PaymentMethod
	(PaymentStatus)(0),             // 1: payment.PaymentStatus
	(*ProcessPaymentRequest)(nil),  // 2: payment.ProcessPaymentRequest
	(*CardDetails)(nil),            // 3: payment.CardDetails
	(*PixDetails)(nil),             // 4: payment.PixDetails
	(*BoletoDetails)(nil),          // 5: payment.BoletoDetails
	(*ProcessPaymentResponse)(nil), // 6: payment.ProcessPaymentResponse
	(*GetPaymentRequest)(nil),      // 7: payment.GetPaymentRequest
	(*GetPaymentResponse)(nil),     // 8: payment.GetPaymentResponse
	(*CancelPaymentRequest)(nil),   // 9: payment.CancelPaymentRequest
	(*CancelPaymentResponse)(nil),  // 10: payment.CancelPaymentResponse
	(*ListPaymentsRequest)(nil),    // 11: payment.ListPaymentsRequest
	(*ListPaymentsResponse)(nil),   // 12: payment.ListPaymentsResponse
	(*timestamppb.Timestamp)(nil),  // 13: google.protobuf.Timestamp
}
var file_proto_payment_proto_depIdxs = []int32{
	0,  // 0: payment.ProcessPaymentRequest.payment_method:type_name -> payment.PaymentMethod
	3,  // 1: payment.ProcessPaymentRequest.card_details:type_name -> payment.CardDetails
	4,  // 2: payment.ProcessPaymentRequest.pix_details:type_name -> payment.PixDetails
	5,  // 3: payment.ProcessPaymentRequest.boleto_details:type_name -> payment.BoletoDetails
	13, // 4: payment.BoletoDetails.due_date:type_name -> google.protobuf.Timestamp
	1,  // 5: payment.ProcessPaymentResponse.status:type_name -> payment.PaymentStatus
	13, // 6: payment.ProcessPaymentResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 7: payment.GetPaymentResponse.payment_method:type_name -> payment.PaymentMethod
	1,  // 8: payment.GetPaymentResponse.status:type_name -> payment.PaymentStatus
	13, // 9: payment.GetPaymentResponse.created_at:type_name -> google.protobuf.Timestamp
	13, // 10: payment.GetPaymentResponse.updated_at:type_name -> google.protobuf.Timestamp
	13, // 11: payment.CancelPaymentResponse.canceled_at:type_name -> google.protobuf.Timestamp
	8,  // 12: payment.ListPaymentsResponse.payments:type_name -> payment.GetPaymentResponse
	2,  // 13: payment.PaymentService.ProcessPayment:input_type -> payment.ProcessPaymentRequest
	7,  // 14: payment.PaymentService.GetPayment:input_type -> payment.GetPaymentRequest
	9,  // 15: payment.PaymentService.CancelPayment:input_type -> payment.CancelPaymentRequest
	11, // 16: payment.PaymentService.ListPayments:input_type -> payment.ListPaymentsRequest
	6,  // 17: payment.PaymentService.ProcessPayment:output_type -> payment.ProcessPaymentResponse
	8,  // 18: payment.PaymentService.GetPayment:output_type -> payment.GetPaymentResponse
	10, // 19: payment.PaymentService.CancelPayment:output_type -> payment.CancelPaymentResponse
	12, // 20: payment.PaymentService.ListPayments:output_type -> payment.ListPaymentsResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_payment_proto_init() }
func file_proto_payment_proto_init() {
	if File_proto_payment_proto != nil {
		return
	}
	file_proto_payment_proto_msgTypes[0].OneofWrappers = []any{
		(*ProcessPaymentRequest_CardDetails)(nil),
		(*ProcessPaymentRequest_PixDetails)(nil),
		(*ProcessPaymentRequest_BoletoDetails)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payment_proto_rawDesc), len(file_proto_payment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_payment_proto_goTypes,
		DependencyIndexes: file_proto_payment_proto_depIdxs,
		EnumInfos:         file_proto_payment_proto_enumTypes,
		MessageInfos:      file_proto_payment_proto_msgTypes,
	}.Build()
	File_proto_payment_proto = out.File
	file_proto_payment_proto_goTypes = nil
	file_proto_payment_proto_depIdxs = nil
}
